### ISSUE TITLE
Have it autogenerate content of licence, setup etc

### ISSUE THREAD

**Issue by Mozzo1000** [NektariosMar/Stamp-Structure_All_My_Python#3]
I think it would be nice to have the script not only create the files but also write in a basic/standard text that is also functional and runnable.

**Example** : 
when running stamp, you should have the option after naming the project to select predefined licenses like MIT, GPL etc. The selected licence would then be written into the LICENCE file.
and/or create a basic setup.py file that is working and will install the project as is.

Would like feedback on this idea, am willing to help with PRs if wanted.

**Comment by NektariosMar** [comment]
I am currently working on this. It is really good and helpful. As for the setup.py part I will look into it, 'cause it isn't as easy as the license part.
Thank you for offering your help for the PRs. You will be informed whenever I need your help.

**Comment by NektariosMar** [comment]
The generation of the selected licence is done. I would appreciate any help for the setup.py
